FROM maven:3.9.6-eclipse-temurin-21

# Set working directory
WORKDIR /app

# Copy source code
COPY . .

# Package the application (this creates a JAR file in /app/target)
RUN mvn clean package

# Expose the port (adjust if needed)
EXPOSE 8080

# Command to run the app
CMD  ["java", "-jar", "target/my-app-1.0-SNAPSHOT.jar"]