# Start from lightweight JDK image
FROM eclipse-temurin:21-jdk-jammy

# Set working directory
WORKDIR /app

# Copy source code into the container
COPY . .

# Build the project inside the container
RUN apt-get update && apt-get install -y maven && \
    mvn clean package

# Move the JAR file to app.jar
RUN mv target/*.jar app.jar

# Expose the app port
EXPOSE 8080

# Run the app
ENTRYPOINT ["java", "-jar", "app.jar"]
